### ISSUE TITLE
Inconsistency between `edit-server-start` and `edit-server-stop`

### ISSUE THREAD

**Issue by xiongtx** [stsquad/emacs_chrome#119]
## Problem

If Emacs is forcefully killed, the `edit-server` process may still occupy the port specified by `edit-server-port`.

When Emacs is restarted, `edit-server-start` will say:

> An edit-server process is already running

But `edit-server-stop` will say:

> No edit server running

This inconsistency is confusing.
## Analysis

The culprit seems to be `edit-server-start`:

``` emacs-lisp
(if (or (process-status "edit-server")
      (null (condition-case err
                    (let ((proc (make-network-process
                                 :name "edit-server"
                                 :buffer edit-server-process-buffer-name
                                 :family 'ipv4
                                 :host (or edit-server-host 'local)
                                 :service edit-server-port
                                 :log 'edit-server-accept
                                 :server t
                                 :noquery t)))
                      (set-process-coding-system proc 'utf-8 'utf-8)
                      proc)
          (file-error nil))))
      (message "An edit-server process is already running")
    ...)
```

This form seems to believe that if no `edit-server` process is running and a new process cannot be started on `edit-server-port`, then `edit-server` must already be running. 
## Suggested Solution

I suggest that we break this into two cases:
- If `(process-status "edit-server")` is `t`, then `An edit-server process is already running`.
- If we cannot start a new process,  then `Cannot start edit-server process`.

The latter case might display some more specific error message (which one(s) exactly is beyond my ken).

**Comment by stsquad** [comment]
Housekeeping, looks like I fixed this.

**Comment by HarrisonMc555** [comment]
I just ran into a situation with a similar result. I was debugging my Emacs startup, and, once I got it figured out, I eventually tried to edit a text area from my browser and it failed. I went to Emacs and ran `edit-server-start` and it said it failed to start. I found the PID of the process listening on port 9292 (`lsof -i tcp:9292` since I'm on Mac), killed it, and ran `edit-server-start` again. After that, it worked.

Does this imply that we still have an issue? I forgot to run `(process-status "edit-server")` before so I don't know what that would have returned :shrug:
