### ISSUE TITLE
if try to exit editing buffer with Ctrl+X Ctrl+S, will invoke edit frame again.

### ISSUE THREAD

**Issue by zw963** [stsquad/emacs_chrome#131]
Relation to https://github.com/stsquad/emacs_chrome/pull/130#issuecomment-347216549

Thanks

**Comment by zw963** [comment]
I rebind C-x C-s to `edit-server-down', so it worked now.

Thanks

**Comment by zw963** [comment]
Hi, i try to fallback restore to default keybinding, i found this issue still exist.

so, i think there still exist some issue about `C-x C-s`, i am wonder why
when i save current buffer,  `edit-server.el` need relaunch my buffer frame.

Previous i think this maybe issue about `maximum frame` function, but when 
i comment maximum frame code, this issue still exist.

Following is recorder gif:

![121.gif](http://zw963.github.io/images/174171944732470.gif)

**Comment by dakra** [comment]
I think `C-x C-s` is supposed to open the frame/window again as it's usually just a 'save' and not save+close. `C-c C-c` should do what you want.

**Comment by stsquad** [comment]
Yeah - it's a save (i.e. update the textarea) and keep editing. But given the way the edit server works it needs to start a new edit session.

**Comment by zw963** [comment]
@stsquad ,  i have a question, why we need update the textarea frequently when we save emacs buffer?

in my point of view, i think, only need save after press C-x C-c .

**Comment by pjones** [comment]
This behavior causes a complete hang when using EXWM.

I'm not exactly sure what's going on but if `edit-server.el` makes any
synchronous calls that trigger a GUI then EXWM can't map the window
any everything hangs.

Since `C-c C-c` works, I think I'm going to remap `C-x C-s` to save
the buffer or a noop since it hangs my Xorg session.  But untangling
the mess of `edit-server-done` would be nice.

**Comment by zw963** [comment]
test hello world!

OKay.
